version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/policypulse_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=H6v@3xP!2qL#9zR8
      - POSTGRES_DB=policypulse
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d policypulse"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:H6v@3xP!2qL#9zR8@db:5432/policypulse
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LEGISCAN_API_KEY=${LEGISCAN_API_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
    depends_on:
      db:
        condition: service_healthy

  # Optional tools container for database management
  tools:
    build:
      context: .
      dockerfile: tools.Dockerfile
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:H6v@3xP!2qL#9zR8@db:5432/policypulse
    depends_on:
      - db
    profiles:
      - tools

volumes:
  postgres_data: